variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - lint

run_tests:
  stage: test
  when: manual
  image: peynmannet/docker-compose-ansible-alpine:latest
  services:
    - docker:20.10.8-dind
  variables:
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "/certs/client"
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: "tcp://docker:2376"
  script:
    - docker compose run -it phpcli phpunit 
  tags:
    - docker
