variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - deploy
  - prepare

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

build_docker_images:
  stage: prepare
  when: manual
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "/certs/client"
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: "tcp://docker:2376"
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:latest -f dev/Dockerfile.phpcli .
    - docker push $CI_REGISTRY_IMAGE:latest
  tags:
    - docker

test:
  stage: prepare
  when: manual
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "/certs/client"
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: "tcp://docker:2376"
  script:
    - docker compose run $CI_REGISTRY_IMAGE:latest composer install
    - docker compose run $CI_REGISTRY_IMAGE:latest phpunit
  tags:
    - docker

lint:
  stage: prepare
  when: manual
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "/certs/client"
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: "tcp://docker:2376"
  script:
    - docker compose run $CI_REGISTRY_IMAGE:latest composer install
    - docker compose run $CI_REGISTRY_IMAGE:latest phpcs
  tags:
    - docker

push_composer_package_dev:
  stage: deploy
  when: manual
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "/certs/client"
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: "tcp://docker:2376"
  script:
    - apk add curl
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=dev "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'
  tags:
    - docker
